var titlepre = 'LCPC'; //Website Title prefix

document.write('	<head>');
document.write('		<!--sets characterset to utf8-->');
document.write('		<meta charset="utf-8">');
document.write('		<!-- makes microsoft browsers use latest rendering engine-->');
document.write('		<meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('		<!--title of the webpage-->');
document.write('		<title>LCPC Home</title>');
document.write('		<!--Set Characterset to UTF-8 -->');
document.write('		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">');
document.write('		<!--Changes viewport for mobile devices-->');
document.write('		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">');
		
document.write('		<!-- Latest compiled and minified CSS -->');
document.write('		<!-- Bootstrap -->');
document.write('		<link href="css/bootstrap.min.css" rel="stylesheet">');
document.write('		<link rel="stylesheet" href="css/stylesheet.css">');
		
document.write('		<!--[if lt IE 9]>');
document.write('		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>');
document.write('		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>');
document.write('		<![endif]-->');	
document.write('		<link href="https://fonts.googleapis.com/css?family=Josefin+Slab:400,400italic" rel="stylesheet" type="text/css">');
document.write('  </head>');

document.write('	<body>');
document.write('		<nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="100">');
document.write('			<div class="container">');
document.write('				<div class="navbar-header">');
document.write('					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">');
document.write('						<span class="sr-only">Toggle navigation</span>');
document.write('						<span class="icon-bar"></span>');
document.write('						<span class="icon-bar"></span>');
document.write('						<span class="icon-bar"></span>');
document.write('					</button>');
document.write('					<div class="socialmediasmall">');
document.write('						<a class="navbar-brand" href="https://www.facebook.com/pages/Lyndhurst-Community-Presbyterian-Church/157862024230469"><img src="Image/icon/facebook.svg" class="socialMedia" > </a></li>');
document.write('						<a class="navbar-brand" href="https://www.twitter.com/GoBoldlyLCPC"><img src="Image/icon/twitter.svg" class="socialMedia"></a></li>');
document.write('						<a class="navbar-brand" href="https://www.facebook.com/pages/Lyndhurst-Community-Presbyterian-Church/157862024230469"><img src="Image/icon/instagram.svg" class="socialMedia"></a></li>');
document.write('					</div>');
document.write('				</div>');
document.write('				<div id="navbar" class="navbar-collapse collapse">');
document.write('					<ul class="nav navbar-nav">');
document.write('						<li class="active"><a href="index.html">Home</a></li>');
document.write('						<li class="dropdown" href="WhoWeAre.html">');
document.write('							<a role="button" aria-haspopup="true" href="WhoWeAre.html">Who We Are <span class="caret"></span></a>');
document.write('							<ul class="dropdown-menu">');
document.write('								<li><a href="FindUs.html">Find Us</a></li>');
document.write('								<li><a href="CoreValues.html">Core Values</a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="dropdown">');
document.write('							<a role="button" aria-haspopup="true" href="Worship.html"> Worship <span class="caret"></span></a>');
document.write('							<ul class="dropdown-menu">');
document.write('								<li><a href="Services.html">Services</a></li>');
document.write('								<li><a href="SermonLinks.html">Sermon Links</a></li>');
document.write('								<li><a href="Music.html">Music</a></li>');
document.write('								<li><a href="SeasonalHappenings.html">Seasonal Happenings</a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="dropdown">');
document.write('							<a role="button" aria-haspopup="true" href="FaithFormation.html"> Faith Formation <span class="caret"></span></a>');
document.write('							<ul class="dropdown-menu">');
document.write('								<li><a href="LearningOpportunities.html">Learning Opportunities</a></li>');
document.write('								<li><a href="Children.html">Children</a></li>');
document.write('								<li><a href="Youth.html">Youth</a></li>');
document.write('								<li><a href="Adult.html">Adult</a></li>');
document.write('								<li><a href="LivingInCommunity.html">Living in Community</a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="dropdown">');
document.write('							<a role="button" aria-haspopup="true" href="WhatWeDo.html"> What We Do <span class="caret"></span></a>');
document.write('							<ul class="dropdown-menu">');
document.write('								<li><a href="Mission.html"> Mission </a></li>');
document.write('								<li><a href="PeaceAndJustice.html">Peace + Justice</a></li>');
document.write('								<li><a href="Tutoring.html">Tutoring</a></li>');
document.write('								<li><a href="Community.html">Community</a></li>');
document.write('								<li><a href="RummageSale.html">Rummage Sale</a></li>');
document.write('								<li><a href="Christmas.html">Christmas Gift Giving</a></li>');
document.write('								<li><a href="MissionCommittee.html">Mission Committee Monthly Initiatives</a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="dropdown">');
document.write('							<a role="button" aria-haspopup="true" href="Contact.html"> Contact <span class="caret"></span></a>');
document.write('							<ul class="dropdown-menu">');
document.write('								<li><a href="CEC.html">CEC </a></li>');
document.write('								<li><a href="Map.html">Map</a></li>');
document.write('								<li><a href="EBlast.html">E-Blast Sign-Up</a></li>');
document.write('								<li><a href="Facility.html">Facility Use</a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('					</ul>');
document.write('					<div class="socialmediabig">');
document.write('						<ul class="nav navbar-nav navbar-right">');
document.write('							<li><a href="https://www.facebook.com/pages/Lyndhurst-Community-Presbyterian-Church/157862024230469"><img src="Image/icon/facebook.svg" class="socialMedia" > </a></li>');
document.write('							<li><a href="https://www.twitter.com/GoBoldlyLCPC"><img src="Image/icon/twitter.svg" class="socialMedia"></a></li>');
document.write('							<li><a href="https://www.facebook.com/pages/Lyndhurst-Community-Presbyterian-Church/157862024230469"><img src="Image/icon/instagram.svg" class="socialMedia"></a></li>');
document.write('						</ul>');
document.write('					</div>');
document.write('				</div>');
document.write('			</div>');
document.write('		</nav>');